export enum TipoAlertaEnum {
  PRODUCTO_AGOTADO            ='PRODUCTO_AGOTADO',
  RIESGO_RUPTURA_STOCK        ='RIESGO_RUPTURA_STOCK',
  PRODUCTO_SIN_MOVIMIENTO     ='PRODUCTO_SIN_MOVIMIENTO',
  SOBRE_STOCK                 ='SOBRE_STOCK',
  BAJA_ROTACION               ='BAJA_ROTACION',
  MARGEN_BAJO                 ='MARGEN_BAJO',
  MARGEN_NEGATIVO             ='MARGEN_NEGATIVO',
  ALTO_CAPITAL_INMOVILIZADO   ='ALTO_CAPITAL_INMOVILIZADO'
}
 